@Pw4("CCCCCCCCCCCCSSSSSSSSSSSSSSSSSSSS")
@eKKKKKKKKKKKKKKK("SSSSSSSSSSSSSSSSSSSSSWSSSSSSSSSS")
@eKKKKKKbkkkkOkkK("SSSSSSSSSSSSSSSSSSSSSSSS        ")
@yKKK44("CCC\0CCCCCyyyyyyyyyyyyyyyyyyyyyyy")
@yKKKKK("")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource == a::"\u{1e}  CCCCCC\u{1c}CCCCCCCCC\0\0\u{1})SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
) when {
  true && (!(!(!true)))
};
