forbid(
  principal is a,
  action == Action::"action",
  resource is a
) when {
  ((true && (if (if (if false then false else false) then false else false) then (false && ([{mmmmmmmmmmmmmmmmm: 7885078839350357357}].containsAll([{m: 7885078839356255597}]))) else (({"": [{"": {"": 7885078839350357357}}]}[""]).containsAll([{"": ip("f2:f200:a4a4:a4c1:c1c1:c1c1:c1ca:c1c1"), oooooooooooomm: 0}])))) && false) && false
};
