@noooo000000000("")
forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ([{"": {"": {"": {"": {}}}, "حDDDD": true}}[""], {"": {"": {"": {"": {}}}, "حDDDD": true}}[""], {"": {"": {"": {"": {}}}, "حDDDD": true}}[""]].contains(({"": {"": {"": {"": {"": {}}}, "حDDDD": true}}}[""])[""]))) && true) && true
};
