forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((({"": {"": {w3: {"": {"": {}, w3: {}}}}}}[""])[""]) == (({"": {"": {"": {"": {"": {}}}, ".": {"": {"": {}}}, "|": {"": {"": true}}}}}[""])[""]))) && ((if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})) == (if (a::"" in a::"") then (if true then {"": {"": {}}, "bian Q": {}} else {"": {"": {}}, "bian Q": {}}) else (if true then context else context)))) && false
};
