forbid(
  principal in jz::a::"",
  action in [jz::Action::"action"],
  resource in jz::a::""
) when {
  (true && (if (({"UUUUUUUUUUUUUUUUUUUU|||||||U": {}}["UUUUUUUUUUUUUUUUUUUU|||||||U"]) has "UUUUUUUUUUUUUUUUUUUU|||||||U") then (if ({} has "UUUUUUUUUUUUUUUUUUUU|||||||U") then ({} has "UUUUUUUUUUUUUUUUUUUU|||||||U") else ({} has "UUUUUUUUUUUUUUUUUUUU|||||||U")) else (({"UUUUUUUUUUUUUUUUUUUU|||||||U": {}}["UUUUUUUUUUUUUUUUUUUU|||||||U"]) has "UUUUUUUUUUUUUUUUUUUU|||||||U"))) && false
};
