forbid(
  principal,
  action,
  resource
) when {
  (true && (if (if (if false then false else false) then (if false then false else false) else (if false then false else false)) then (if (if false then false else false) then (if false then false else false) else (if false then false else false)) else (if (if false then false else false) then (if false then false else false) else (if false then false else false)))) && (if (if (if false then false else false) then (if false then false else false) else ([].isEmpty())) then false else false)
};
