permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource in a::"FFFFFF\0FFFFFF\0"
) when {
  ((true && (((false == false) == (false == false)) == ((false == false) == ((ip("70.70.70.70")).isIpv4(ip("70.70.70.70"), ip("82.6z.51.85")))))) && (((true == true) == (!true)) == ((if true then resource else resource) in action))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))
};
