@F("")
@LS33TuRa3zERR("\u{3}")
@LS3T1ed("")
permit(
  principal,
  action == h::T0::A01000000::Action::"action",
  resource == h::T0::A01000000::a::":~"
) when {
  ((true && (h::T0::A01000000::a::"}}" in h::T0::A01000000::a::"}}")) && (if ((decimal("\u{7f}")).lessThanOrEqual({"[@[": decimal("0.")}["[@["])) then (h::T0::A01000000::a::"}}" in h::T0::A01000000::a::"}}") else ("\0\0" like "*\u{1d}*@*["))) && ((if ("\0\0" like "*\u{1d}*@[") then (if false then "z~" else "") else "") like "")
};
