permit(
  principal is a,
  action == Action::"action",
  resource is a
) when {
  ((true && ((decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000)).lessThanOrEqual(decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000), decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000), decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000)))) && ((decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000)).lessThanOrEqual(decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000)))) && ((decimal(a::"\0\0\0\0\0\0F3j000\0\0\0\0\0{{{{{{{{{{{{{{{".gWQWWW0000000000)).lessThanOrEqual(decimal(principal.r), context["ox{{{\0\0\0\0\u{14}\0\0\0\0\0\0\0\0\0\0\0\0\0\0       #"]))
};
