permit(
  principal == t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::N::"",
  action in [t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource is t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::B in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::z::""
) when {
  true
};
