forbid(
  principal is a in a::"xxxxI",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::"rox"
) when {
  ((true && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if false then false else false) else (if false then false else false)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then ((if true then 9187201950429507169 else 6148821046635397247) == 0) else false)
};
