permit(
  principal == a::"\n",
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([{"": [[[decimal("108510259614647.5056"), decimal("0.1")], [decimal("0.1"), decimal("-9042521182202223.177"), decimal("-904252161764651.7532")]], [[decimal("0.1"), decimal("0.1"), decimal("7205759403792.7935")], [decimal("0.1"), decimal("-28147497671.656"), decimal("0.1")], [decimal("0.1"), decimal("0.0"), decimal("0.0")]]]}[""], []].containsAny([]))) && false) && false
};
