@D31bbkR1FR333("\u{3}")
@Da33NNg0u00RRw0("\u{1d}@[")
@Da33NNg0u00RRw1("")
@Dc3("")
@H("")
@UA6pW6m3("@[")
@ctRa3zERRei33("")
@d("")
@dt3a("=\u{e}")
@duRa("=\u{e}")
@jp_a("&\u{3}\u{7}")
@rzE("")
@vbkR1FR3333333("\u{1d}w")
permit(
  principal,
  action == Action::"action",
  resource in a::""
) when {
  ((true && (principal in (context[""]))) && ((({"\0": context}["\0"])["$=\u{e}"])[""])) && true
};
