@NRKKKKK("SSSSSSSSSSSSSSSSSSSS+")
@eKKKKwRRNT3ER3D4("")
forbid(
  principal is jz::a,
  action == jz::Action::"action",
  resource in jz::a::""
) when {
  (true && (if ((if true then false else false) || ((ip("2001:948:7a3a:993b:993e:3e3e:3e3e:c1c1/126")).isInRange(ip("5ff:af0f:120:6e61:6962:6544:ffff:ff69/105")))) then (([(datetime("4975-02-08T15:13:13+1343")).offset(duration("-7450967821640623975h"))].containsAll(["", ""])) && ((decimal("882550108624535.4106")).lessThan(decimal("12150841071156.6138")))) else true)) && true
};
