permit(
  principal,
  action == Action::"action",
  resource == a::""
) when {
  true && (!((((datetime("3385-02-18")).offset(duration("3834170449818156647ms"))).toTime()) <= ((if false then {"JJJJJJJJJJJJJJJJJJ0\u{1}\0\0GJJJJJJJ\0\0\0\0\0": duration("36735244019335810ms")} else {"JJJJJJJJJJJJJJJJJJ0\u{1}\0\0GJJJJJJJ\0\0\0\0\0": duration("1676976733981213314m")})["JJJJJJJJJJJJJJJJJJ0\u{1}\0\0GJJJJJJJ\0\0\0\0\0"])))
};
