permit(
  principal in A::A::j::a::"",
  action == A::A::j::Action::"action",
  resource == A::A::j::a::"sssssss^3"
) when {
  ((true && (!false)) && ((((decimal("1766117500.9296")).greaterThan(decimal("6898896.895"), decimal("-822876530503014.4702"), decimal("7955375428823973.8879"), decimal("-109747362.3687"))) && (!false)) && (A::A::j::a::"sssssss^3" in A::A::j::a::"sssssss^3"))) && ("\r\0" == "\r\0")
};
