@A("")
permit(
  principal,
  action,
  resource
) when {
  (true && (((datetime("")).offset((datetime("9578-12-01")).durationSince((datetime("5535-04-08T15:15:15.535+0015")).offset(duration("-1d7090147955172179967h2125409m"))))) == (if false then (if false then (datetime("0000-01-01")) else ((datetime("5535-04-08T15:15:15.535+0015")).offset(duration("-1")))) else (if false then (datetime("9540-06-08T15:15:15.535+0015")) else ((datetime("5471-04-08T15:15:15.535+015")).offset(duration("0ms"))))))) && true
};
