permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([{"": [[[decimal("-576309933658846.32")], [decimal("0.215"), decimal("0.1"), decimal("0.1")]], [[decimal("331464932574468.5055"), decimal("-25508669764.4032"), decimal("612489549322387.4559")], [decimal("-1579.321"), decimal("-5.4785"), decimal("-15503113951.6417")], [decimal("0.1"), decimal("0.0"), decimal("0.232")]]]}[""], [[[decimal("0.1"), decimal("0.1"), decimal("0.1")], [decimal("0.1"), decimal("0.1"), decimal("0.1")], [decimal("-417752.6785"), decimal("0.1"), decimal("0.1")]], [[decimal("0.1"), decimal("0.1"), decimal("858993.4592")], [decimal("0.1"), decimal("0.250"), decimal("0.0")], []], []]].containsAny([]))) && false) && false
};
