@_ggg("")
permit(
  principal in A::A::j::a::"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0sssssss^4",
  action == A::A::j::Action::"action",
  resource == A::A::j::a::"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0sssssss^4"
) when {
  ((true && (!false)) && ((((ip("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")).isMulticast()) && ({"\r\0": decimal("389070055955258.491")} == context)) && (((decimal("1766117500.9296")).greaterThan(decimal("831911987638716.6720"))) && false))) && ((false && (false == false)) && (false && (action in [action])))
};
