permit(
  principal in a::"",
  action,
  resource
) when {
  (true && ((if ({"z\0\0\0\0\0\0\0 v3              ": false}["z\0\0\0\0\0\0\0 v3              "]) then (if true then {"z\0\0\0\0\0\0\0 v3              ": false} else {"z\0\0\0\0\0\0\0 v3              ": false}) else (if false then {"z\0\0\0\0\0\0\0 v3              ": false} else {"z\0\0\0\0\0\0\0 v3              ": false}))["z\0\0\0\0\0\0\0 v3              "])) && ("z\0\0\0\0\0\0\0 v3              " like ".....")
};
