@A00000000("")
forbid(
  principal == a::"\u{f}",
  action == Action::"action",
  resource is a in a::"\u{f}"
) when {
  ((true && ((if ([].contains({"": false})) then ({"***9]": [{"": {"": {"": 67318718123247495}}}, {"": {"": context}}, {"": {"": {"": 524466253076037715}}}]}["***9]"]) else ({GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG: [{"": {"": {"": 5136152271503443783}}}, {"": {"": {"": 5136152245733640007}}}, {"": {"": {"": 327}}}]}.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG)).contains(context))) && false) && true
};
