@A("")
@EWT333300RYwn("")
@EWTTTTTTTTTTT("\u{1d}\u{1d}\u{1d}\u{1d}")
@F("")
@Igledddedddd05c("")
@J("")
@JWWW0WWWW("")
@L3("\0\0\0")
@Q("")
@QWWWWW("")
@Qnnnnn("")
@V("")
@dTTTTTTN1yT3N("")
@dTTTTTTTTTTTT("\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}")
@h("EWTTTT")
@mT3N1("\u{1d}")
@p("")
@r("")
@r3("")
@v("\0\0\u{1d}")
@w("")
permit(
  principal,
  action == r::r::h::r::Action::"action",
  resource in r::r::h::r::a::" \0\0\0"
) when {
  true && (r::r::h::r::a::"isionn" in ((principal.p_).p_))
};
