forbid(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((({"lll\'": [[[false, false, false], [true, true], [true, true, true]], [[false, true, true], [true, true, true], []], []]}["lll\'"]).containsAll({"l\'": [[[true, true, true], [], [true, true, false]], [[false, false], [false]], [[false, false, false]]]}["l\'"])) && false)) && false) && false
};
