@D3S1S3T1eddb0("\u{e}")
@LRaEzRR("")
@rzE("")
@v3X33Sw1S3("\u{1d}wDebian ")
@vREb33bR3X("")
@vbbb("")
forbid(
  principal == t::tFFugC04uq123::r::r::r3z0333SRRRZX4u::p233333V33z0333SR::t::P::"",
  action,
  resource is t::tFFugC04uq123::r::r::r3z0333SRRRZX4u::p233333V33z0333SR::t::y
) when {
  (true && ((t::tFFugC04uq123::r::r::r3z0333SRRRZX4u::p233333V33z0333SR::t::y::"" in t::tFFugC04uq123::r::r::r3z0333SRRRZX4u::p233333V33z0333SR::t::r::"") || (if (if true then true else false) then (if true then true else false) else (1026256821781362461 <= 6575356606787983769)))) && ((ip("ffd~")).isLoopback())
};
