forbid(
  principal,
  action,
  resource
) when {
  ((true && (if (if (if false then false else false) then (if false then true else false) else (action in [principal, action])) then (a::"" in a::"") else false)) && (if (if ("GGGGGG" like "**G***G") then (if true then false else false) else (if false then false else false)) then (if ("GGGGGGGGGGGGGG" like "*") then true else true) else true)) && true
};
