permit(
  principal is a in a::"\n",
  action in [Action::"action"],
  resource
) when {
  ((true && ([{"": [[[decimal("-576309933658846.32")], [decimal("0.1"), decimal("0.1"), decimal("0.1")]], [[decimal("0.1"), decimal("0.129"), decimal("429496.7295")], [decimal("0.1"), decimal("795375428823973.8879"), decimal("0.1")], [decimal("0.0"), decimal("54410.4809"), decimal("0.1")]]]}[""], if true then [[[decimal("0.1"), decimal("0.0"), decimal("0.0")], [], []], [], []] else []].containsAny([]))) && false) && false
};
