@A000000000("")
@Urrrrrrrrr("")
forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})) == (if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else ({"": {"": {"": {"": {}}}}}[""])))) && ((if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})) == (if ({"": false}[""]) then (if true then context else {"": {"": {"": {}}}}) else ({"": {"": {"": {"": {}}}}}[""])))) && ((if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})) == (if ("" like "") then (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}}) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})))
};
