forbid(
  principal,
  action in [Action::"action",Action::"action"],
  resource in a::"FFFFFFFFFFFFF\0"
) when {
  ((true && (((false == false) == (false == false)) == ((false == false) == ((ip("70.70.70.70")).isIpv4(ip("70.70.70.70"), ip("82.6z.51.85")))))) && (((false == false) == (false == false)) == ((false == false) == false))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))
};
