permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([{"": [[[decimal("108510259614647.5056"), decimal("0.1")], [decimal("0.1"), decimal("0.1"), decimal("0.1")]], [[decimal("-1465.1807")], [decimal("-557019330852683.7761"), decimal("-557019330853190.3822"), decimal("²557019330853190.3822")]]]}[""], [[[decimal("0.4095"), decimal("0.0"), decimal("0.0")], [], []], [], []]].containsAny([]))) && false) && false
};
