@A("")
@F("")
@K("")
@P("")
@P000000("")
@PXccccc("")
@Pcc3ERJ("\u{1d}@")
@Pcccccc("")
@PcccepcccebmmmdWH("ca")
@Pebmmma("")
@V("")
@_YWc("")
@d1RSNRc("")
@gcccccccHcZkk("a")
@hRcW33cccccacc("")
@nk_cccccccc333("")
@r("")
@r33("")
@sWd000c("")
@u("")
@u3("\0\0")
@uG("")
@vJST1RSNRcW33cc("")
permit(
  principal == a::"\0\0\0\0\0**",
  action == Action::"action",
  resource == a::"\0\0\0\0\0**"
) when {
  ((true && (resource in resource)) && (resource in resource)) && (resource in a::"\0\0\0\0\0**")
};
