permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([{"": [[[decimal("-576309933658846.32")], [decimal("0.1"), decimal("0.1"), decimal("6.5535")]], []]}[""], [[[decimal("-3764791808517.7345"), decimal("0.1"), decimal("0.1")], [decimal("0.1"), decimal("0.1"), decimal("0.1")], [decimal("0.1"), decimal("0.1"), decimal("0.1")]], [[decimal("0.1"), decimal("-6.4390"), decimal("0.1")], [decimal("0.1"), decimal("0.0"), decimal("0.0")], []], []]].containsAny([]))) && false) && false
};
