permit(
  principal is t,
  action == Action::"action",
  resource
) when {
  (true && (((principal in resource) || (1080750912556302401 <= (-181014141953639))) || (true && (((datetime("9624-03-30T22:32:34.247+0033")).offset(duration("4629771063952162880d"))) <= ((datetime("9624-05-16")).offset(duration("-4629771061636907072ms"))))))) && ({"": {"@@@@@@@@@@@@@@@B@@@@@@@@@@": false}["@@@@@@@@@@@@@@@B@@@@@@@@@@"]}[""])
};
