forbid(
  principal in a::"",
  action == Action::"",
  resource in a::""
) when {
  (true && (if (({"": [":"]}[""]).containsAny({"\u{e}VV": ["\u{e}VV", "\u{e}VV"]}["\u{e}VV"])) then (({"\u{e}VV": ["\u{e}VV", "\u{e}VV"]}["\u{e}VV"]).containsAny({"": ["\u{e}VV", "\u{e}VV"]}[""])) else (({"\u{e}VV": ["\u{e}VV", "\u{e}VV"]}["\u{e}VV"]).containsAny({"\u{e}VV": ["\u{e}VV", "\u{e}VV"]}["\u{e}VV"])))) && (((if false then {"": ["\u{e}VV", "\u{e}VV"]} else {"": ["\u{e}VV", "\u{e}VV"]})[""]).containsAny((if false then {"\u{e}VV": ["\u{e}VV", "\u{e}VV"]} else {"\u{e}VV": ["\u{e}VV", "\u{e}VV"]})["\u{e}VV"]))
};
