permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource in a::"FFFFFFFFFFFFFF\0"
) when {
  ((true && (((false == false) == (false == false)) == ((false == false) == ((ip("70.70.70.70")).isIpv4(ip("70.70.70.70"), ip("122.10.169.0")))))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))
};
