permit(
  principal == a::"\u{7f}\u{e}",
  action in [Action::""],
  resource == a::"\u{7f}\u{e}"
) when {
  (true && (((-(72463799287616)) * (-(72463799287616))) <= (-(-(0))))) && ((((datetime("3551-01-01")).toDate()).toDate()) <= (if false then (if false then (datetime("0000-01-01")) else (datetime("2428-0-07"))) else (((datetime("2685-02-20T13:25:25.685Z")).offset(duration("-0d0h0m0s0ms"))).offset(duration("-0d0h0m0s0ms")))))
};
