forbid(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((({"lll\'": [[[true, true, true], [true, true, false], [true, true, false]], [[], [false, false]], [[true, true, false], []]]}["lll\'"]).containsAll({"l\'": [[[true, true, true], [false, false], [false, true]], [[true, false]], [[false, false, false]]]}["l\'"])) && false)) && false) && false
};
