@B("")
@g("")
permit(
  principal in jz::a::">>",
  action == jz::Action::"action",
  resource in jz::a::">>"
) when {
  (true && (if (if (action has "UUUUUUUUUUUUUUUUUUUUUU>>>>>>") then (if true then true else true) else (if false then false else false)) then ((decimal("UUUUUUUUUU")).lessThan(decimal("UUUUUUUUUU"))) else ((decimal("UUUUUUUUUUUUUUUUUUUUUU>>>>>>")).lessThan(decimal("UUUUUUUUUUUUUUUUUUUUUU>>>>>>"))))) && true
};
