permit(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ({kkkkkkk: principal, "k\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}_": principal, "\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}": principal} == principal)) && false) && false
};
