@H("")
@g3("h\u{1}/h")
@l4445424("")
@n("")
forbid(
  principal is jz::a,
  action == jz::Action::"action",
  resource in jz::a::""
) when {
  (true && (if ((if true then false else false) || ((ip("7a7a:7a7a:7a2c:7a7a:7a7a:7a7a:7a7a:7bc1")).isInRange(ip("122.122.122.122")))) then (74661237572501504 == ({"": (-504965456172324609)}[""])) else (false || (jz::a::"".hasTag(""))))) && (!((if false then {"": false} else {"": false})[""]))
};
