@IzzzzzzzzWW("    ")
@LWWWzzz("=====")
@LedEdb30RJc3T("")
forbid(
  principal == XNAeppN::XNNNNNN::"",
  action == XNAeppN::Action::"======",
  resource == XNAeppN::XNNNNNN::""
) when {
  true && (if (if (if true then true else true) then (if true then true else true) else (if true then false else false)) then ((principal.getTag("                               ")) == "\0\0") else (false || ((ip("229.3.2555.91")).isLoopback())))
};
