forbid(
  principal,
  action in [A::Action::"action"],
  resource
) when {
  ((true && ((if (A::vR::"".g123333) then ({"": ip("c0c0:42ff:ffff:5b01:9999:1933:21:6799")}[""]) else (ip("\n\n\n\n\n\n\n\n\n\n\n\n\n\n"))).isMulticast())) && (if (if (if false then false else false) then (if false then false else false) else (if false then false else false)) then (if (if false then false else false) then (if false then false else false) else (if false then false else false)) else (if (if false then false else false) then (if false then false else false) else false))) && false
};
