forbid(
  principal,
  action in [Action::"\u{1d}[\u{1d}"],
  resource
) when {
  ((true && (((if false then {"": ["", ""]} else {"": ["", ""]})[""]).containsAny((if false then {"": ["", ""]} else {"": ["", ""]})[""]))) && (((if false then {"": ["\u{18}\r", ""]} else {"": ["", ""]})[""]).containsAny((if false then {"": ["", ""]} else {"": ["", ""]})[""]))) && (["ng", resource.getTag("")].containsAny([]))
};
