permit(
  principal in t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::r::"\0\0\0vzvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvDebian ",
  action in [t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource in t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::r::"\0\0\0vzvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvDebian "
) when {
  (true && (principal has vvvvvvvvvvvvvvvvvvvvvvv)) && (principal has "H5vvvvvvvvvvvvvvvvvvvvv][")
};
