permit(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((if ({"": false}[""]) then (if false then {k: resource, kkkk: a::"", kkkkkkkkkkkkkkkkAk: a::""} else {k: a::"", kkkk: resource, kkkkkkkkkkkkkkkkAk: resource}) else (if false then {k: resource, kkkk: action, kkkkkkkkkkkkkkkkAk: action} else {k: action, kkkk: action, kkkkkkkkkkkkkkkkAk: action})) == false)) && false) && false
};
