@Mnn("")
@fVVVVVV("\u{1f}\u{1f}\u{1f}\u{1f}\0\0\0\0\0}}}}}}}}}}}}}}}}}}}}}}}}}}g")
@g33fKKKKKKKKK("SSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
@r("")
permit(
  principal is a,
  action == Action::"action",
  resource is a
) when {
  (true && (true && (((ip("5353:5353:5353:5353:5353:5353:0:2a/83")).isMulticast()) && (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))
};
