permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource in a::"FFFFFFFFFFFFF\0"
) when {
  ((true && ((if (if false then false else false) then (false == false) else (false == false)) == ((false == false) == (false == false)))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && (((decimal("-(------\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{10}\0\0\0")) == (decimal("---"))) == ((if true then [] else []).isEmpty()))
};
