permit(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((if ({"": false}[""]) then (if false then {"kkkkkkkkkkkkkkkkk{kkkkkk": resource} else {"kkkkkkkkkkkkkkkkk{kkkkkk": resource}) else (if true then {"kkkkkkkkkkkkkkkkk{kkkkkk": resource} else {"kkkkkkkkkkkkkkkkk{kkkkkk": action})) == (duration("-2181169794d")))) && false) && false
};
