permit(
  principal,
  action in [Action::"action"],
  resource
) when {
  true && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then ((if true then a::"\0\0\0\0\0SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS" else a::"\0\0\0\0\0SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS") in (if true then a::"\0\0\0\0\0SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS" else principal)) else false)
};
