permit(
  principal in A::vRNN001gNg001R::F::v5cbgXUcOOOOOO::L::BW33f1Ff31::i9::r3R::"aaaa^",
  action in [A::vRNN001gNg001R::F::v5cbgXUcOOOOOO::L::BW33f1Ff31::i9::Action::"action"],
  resource in A::vRNN001gNg001R::F::v5cbgXUcOOOOOO::L::BW33f1Ff31::i9::r3R::"aaaa^"
) when {
  (true && (A::vRNN001gNg001R::F::v5cbgXUcOOOOOO::L::BW33f1Ff31::i9::r3R::"aaaa^" in A::vRNN001gNg001R::F::v5cbgXUcOOOOOO::L::BW33f1Ff31::i9::r3R::"aaaa^")) && ((({"aaaaaaaaaaa\0\0\0\0": {"aaaaaaaaaaa\0\0\0\0": resource}}["aaaaaaaaaaa\0\0\0\0"])["aaaaaaaaaaa\0\0\0\0"]) has "aaaaaaaaaaa\0\0\0\0")
};
