permit(
  principal == A::A::a::"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
  action == A::A::Action::"",
  resource == A::A::a::"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
) when {
  ((true && ((ip(context[""])).isMulticast())) && (if (if false then false else false) then true else true)) && (({"": ip("ff03:ff3f:3dff:ff1f:ffff:ffff:fffe:fd20")}[""]).isMulticast())
};
