@A("")
@F("")
@Iccc__Y("bi")
@K("")
@LRSNRcW33cccc("")
@P("")
@PcYWd000cPgYW("")
@PccVccc("")
@PccXccc("")
@Pccc3ER("")
@Pcccccc("")
@Pccebmm("")
@_YWc("")
@d1RSNRc("")
@g("")
@gccccccc7cccc("")
@hccWd00("")
@mT1Rcccccc("")
@n__33GGGGGGGGG("")
@n__eYBZg_____3("")
@nk_ccccccccc33("")
@r("")
@sWd000c("")
@uG("")
@vJST1Rccc00RRwR("\u{e}")
@yGGGGGG3("\0\0")
permit(
  principal == a::"\0\0\0\0\0**",
  action == Action::"action",
  resource == a::"\0\0\0\0\0**"
) when {
  ((true && (resource in resource)) && (resource in resource)) && (resource in a::"\0\0\0\0\0**")
};
