forbid(
  principal in gCCCCCCCCCCC::gC4::Y44424a4sss4::a::"\u{2}",
  action in [gCCCCCCCCCCC::gC4::Y44424a4sss4::Action::"action"],
  resource == gCCCCCCCCCCC::gC4::Y44424a4sss4::a::"\u{2}"
) when {
  (true && ((if ({"": false}[""]) then (if false then {"": true} else {"": false}) else (if false then {"": false} else {"": false}))[""])) && ([[[decimal("-188095404639783.8710"), decimal("-188084449378999.3499")], [decimal("1506.6597")]], []] == [])
};
