@B("i")
@B33344("\'ggg\ngfg")
@F("")
@IEn("\0J\n)")
@L3__RRRw03ERV("\0\0\0\u{3}[@")
@P("bian \u{1}\u{f}")
@P2nn13("")
@Pg("")
@Pn("yA")
@T("\0\0")
@_YlW1Fnnw2nn13("")
@i400000("")
@i4W33f3("")
@iKKKKKK("SSSSSSSSS\u{f}")
@ideeeAe("g")
@r("")
@r333332KKKKKKKK("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
@v33uTSRa3zERRS3("@J<")
@wmm33444deeeAee("")
@z("")
permit(
  principal,
  action == A::A::Action::"\u{1f}\u{1d}@J<",
  resource
) when {
  true
};
