forbid(
  principal is a,
  action in [Action::"action"],
  resource in a::""
) when {
  (true && ([[[["wwwww\0\0\0\0\0@", "", ""], [""], [""]], [[""], [], [""]], [["", "", ""], [""], ["", "", ""]]], [[["", "", ""], ["wwww", "wwwwwww::", ""], []], [[]], []], [[["wwwww"], ["wwwwwwwwwwwwwwwwww:", ":", ""], []], [[]], [["ww\u{b}\0\0\0www", "wwwww\u{f}wwwww", ""], [], []]]].containsAny([]))) && false
};
