@eKKKKKKKKKK33333("")
@eKKKKKKKKKKKKKKK("")
@yA("")
forbid(
  principal is jz::a,
  action == jz::Action::"action",
  resource in jz::a::""
) when {
  (true && (if ((if true then false else false) || ((ip("2001:948:7a3a:993b:993e:3e3e:3e3e:c1c1/126")).isInRange(ip("5ff:af0f:120:6e61:6962:6544:ffff:ff69/105")))) then (([(datetime("4975-02-08T15:13:13.087Z")).offset(duration("-2864783874392024842d8825501086245354087h"))].containsAll([ip("5353:5353:5353:5301:afaf:4179:af67:ffff/83")])) && true) else true)) && true
};
