@A("")
@r("")
permit(
  principal in QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"",
  action in [QI00dppp::ID000pppppppn::IpppppppppppT::M::Action::"action"],
  resource == QI00dppp::ID000pppppppn::IpppppppppppT::M::a::""
) when {
  ((true && ((if (QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" in QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"") then (if true then QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" else QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"") else (if true then QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" else QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"")) in (if (QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" in QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"") then (if true then QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" else QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"") else (if true then QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"" else QI00dppp::ID000pppppppn::IpppppppppppT::M::a::"")))) && (principal is QI00dppp::ID000pppppppn::IpppppppppppT::M::a)) && ("rrrrrA\n" like "")
};
