forbid(
  principal in Cr9s0ZZZ3oZZZZ::CYrgmlh1g::v::v::v::tgYlW00kl3Tulllll::a::"",
  action == Cr9s0ZZZ3oZZZZ::CYrgmlh1g::v::v::v::tgYlW00kl3Tulllll::Action::"action",
  resource in Cr9s0ZZZ3oZZZZ::CYrgmlh1g::v::v::v::tgYlW00kl3Tulllll::a::""
) when {
  (true && ((if (resource has UhhhhhhhZZZZ) then (if false then resource else resource) else (if false then resource else resource)) has UhhhhhhhZZZZ)) && ((if (Cr9s0ZZZ3oZZZZ::CYrgmlh1g::v::v::v::tgYlW00kl3Tulllll::a::"" has CZZZZZZZZ) then principal else Cr9s0ZZZ3oZZZZ::CYrgmlh1g::v::v::v::tgYlW00kl3Tulllll::a::"") has UhhhhhhhZZZZ)
};
