forbid(
  principal == a::"\0",
  action,
  resource
) when {
  ((true && ((if true then (decimal("\u{3}       \u{1e}  CCCCCC\u{1c}CC,CCCCCCC")) else (decimal(""))).greaterThanOrEqual(decimal(if true then "" else "")))) && (!(!(!true)))) && ({"": if true then {"": {"": "CC\0S"}} else {"": {"": ""}}} == (if true then (if true then {"": {"": {"": "SS"}}} else {"": {"": {"": ""}}}) else (if true then {"": {"": {"": "SSS"}}} else {"": {"": {"": "SSS "}}})))
};
