@A0000000000000("")
@_WxZZZ("##D")
permit(
  principal,
  action == r::V::QN::r::Action::"action",
  resource == r::V::QN::r::A::""
) when {
  ((true && (((r::V::QN::r::A::"".GRRmST3N).GRRmST3N) in ((r::V::QN::r::A::"".GRRmST3N).GRRmST3N))) && (((r::V::QN::r::A::"".GRRmST3N).GRRmST3N) in ((r::V::QN::r::A::"".GRRmST3N).GRRmST3N))) && (((action.GRRmST3N).GRRmST3N) in ((r::V::QN::r::A::"".GRRmST3N).GRRmST3N))
};
