@Urrrrrrrr0("")
@Urrrrrrrrr("")
forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((if ("" like "") then (if true then {"": {"": {"": {}, w3: {}}}, ".": {"": {"": {}}, "\0": {"": {}, "\r\0": {}}}} else {"": {"": {"": {}, w3: {}}}, ".": {"": {"": {}}, "\0": {"": {}, "\r\0": {}}}}) else (if true then {"": {"": {"": {}, w3: {}}}, ".": {"": {"": {}}, "\0": {"": {}, "\r\0": {}}}} else {"": {"": {"": {}, w3: {}}}, ".": {"": {"": {}}, "\0": {"": {}, "\r\0": {}}}})) == (if ("" like "") then (if true then {"": {"": {"": {}, "\0\0\0\u{8}": {}}}} else {"": {"": {"": {}, "\0\0\0\u{8}": {}}}}) else (if true then {"": {"": {"": {}, "\0\0\0\u{8}": {}}}} else {"": {"": {"": {}, "\0\0\0\u{8}": {}}}})))) && ("" like "")) && ("" like "")
};
