permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ((((ip("2c2c:2c2c:2c2c:2c2c:2c2c:2c2c:2c2c:2c2c")) == (ip("44.41.44.44"))) && ([].containsAny([]))) == ((if false then [] else []).containsAny(if false then [decimal("383402915957591.3219"), decimal("383402916041806.3669"), decimal("383402916041806.3669")] else [decimal("383402916041806.3669")])))) && (a::"\n".hasTag(if (action.hasTag("5555555\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}R\u{3}\u{3}\u{3},,,,,")) then "\u{3}\u{3}" else "\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}Qn\u{3}\u{3}\u{3}\u{3}\u{3}\u{3},,,,,,,,,,"))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [decimal("14349704694.2594"), decimal("0.0"), decimal("0.0")])).containsAny([]))
};
