forbid(
  principal is a in a::"",
  action == Action::"action",
  resource == a::""
) when {
  ((true && (a::"".Ag)) && ((false && ([[true, false, false], []].contains([]))) && (({"": [[[false], [], []], [], []]}[""]).contains(context.llllllllllllll)))) && ([[[[true, true, false], [], []], [], []], [], []].contains(({"": {lllllllPP: [[[true, true, true], [true, true, true], [true, true, true]], [[false, false], []], []]}}[""]).lllllllPP))
};
