forbid(
  principal == A::vRNN001gNg001R::F::v5cVVVVVVVVVVV::mzzzzzzzzTzz3::r::i9::mzYYYYYYYYYYY::"S",
  action in [A::vRNN001gNg001R::F::v5cVVVVVVVVVVV::mzzzzzzzzTzz3::r::i9::Action::"action",A::vRNN001gNg001R::F::v5cVVVVVVVVVVV::mzzzzzzzzTzz3::r::i9::Action::"action",A::vRNN001gNg001R::F::v5cVVVVVVVVVVV::mzzzzzzzzTzz3::r::i9::Action::"action"],
  resource
) when {
  ((true && (A::vRNN001gNg001R::F::v5cVVVVVVVVVVV::mzzzzzzzzTzz3::r::i9::A::"" in A::"")) && false) && false
};
