permit(
  principal is LS::rN130000RRwnN::T0::A0RRw03T::m33Tu5cZgYlWRa::I::w0004233::a,
  action in [LS::rN130000RRwnN::T0::A0RRw03T::m33Tu5cZgYlWRa::I::w0004233::Action::"action"],
  resource == LS::rN130000RRwnN::T0::A0RRw03T::m33Tu5cZgYlWRa::I::w0004233::a::"\u{1d}"
) when {
  ((true && (true && ((context["[@["]) in LS::rN130000RRwnN::T0::A0RRw03T::m33Tu5cZgYlWRa::I::w0004233::a::"\u{1d}"))) && false) && false
};
