forbid(
  principal is A::A::A::A::A::A::G660000::a in A::A::A::A::A::A::G660000::a::"",
  action in [A::A::A::A::A::A::G660000::Action::"action",A::A::A::A::A::A::G660000::Action::"action",A::A::A::A::A::A::G660000::Action::"action"],
  resource is A::A::A::A::A::A::G660000::a in A::A::A::A::A::A::G660000::a::""
) when {
  ((true && (434041037028460038 <= 434041037028460038)) && true) && true
};
