@ye("")
forbid(
  principal,
  action,
  resource
) when {
  ((true && (if ((if false then {"": false} else {"": false})[""]) then ((if false then {"": false} else {"": false})[""]) else ((if false then {"": false} else {"": false})[""]))) && ((if ({"": false}[""]) then (if false then {"": false} else {"": false}) else (if false then {"": false} else {"": false}))[""])) && ((if ({"": false}[""]) then (if false then {"": false} else {"": false}) else (if false then {"": false} else {"": true}))[""])
};
