permit(
  principal is a,
  action in [Action::"action"],
  resource is a
) when {
  true && ((if false then (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))) else (if false then (ip("::")) else (ip("0.0.0.0")))).isInRange(if false then (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))) else (ip("")), if false then (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))) else (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))), if false then (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))) else (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))), if false then (if false then (ip("157.148.0.0")) else (ip("0.65.0.0"))) else (if false then (ip("0.0.0.0")) else (ip("0.0.0.0")))))
};
