forbid(
  principal,
  action,
  resource is a in a::""
) when {
  true && (!(if (action in action) then (((datetime("\u{8b}\u{8b}\u{8b}\u{8b}-08-16T19:19:19.822+0419")).offset(duration("-1d54255126}9\u{8b}\u{8b}\u{8b}î\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}h"))) == (ip("ffff:199:99ff:ffff:ffff:ffff\u{8b}\u{8b}fff:ffff/126"))) else ((ip("\u{8b}b3f:8282:206e:6962:0:48:8b8b:8b8b/10")).isInRange(ip("0.0.0.0")))))
};
