@A("")
@Epn("")
@K("")
@LRSNRcW33cccc("")
@P("")
@P3ERJST("")
@PF3_33H9H3n3H("\u{f}h")
@PcYW000dcPgYW("")
@Pcccccc("d000cP")
@Pccebmm("")
@Pf("#\"#####")
@bc("")
@gd000cPgYWccc("")
@hRcW33ccccXccc("")
@hcccccc("")
@jZ("")
@n_33GG00000000("")
@nk001_cccccc33("")
@qpppraR("YlW")
@r("")
@sWd000c("")
@uG("")
@v3ERJST1("")
@ybmmmaH("")
permit(
  principal == a::"\0\0\0\0\0**",
  action == Action::"action",
  resource == a::"\0\0\0\0\0**"
) when {
  ((true && (resource in resource)) && (resource in resource)) && (resource in a::"\0\0\0\0\0**")
};
