@A00000000000("")
permit(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then (if false then principal else principal) else (if true then a::"" else principal)))) && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)))) && ((if (principal in principal) then principal else principal) in principal)
};
