permit(
  principal,
  action in [w::Action::"--"],
  resource == w::a::"\0"
) when {
  (true && ((if true then (if true then [(datetime("1565-10-15T21:45:45.834Z")).offset(duration("6004234345560363860ms"))] else [datetime("1007-0022--05T18:42:42.169Z"), datetime("9469-06-01T21:45:45.565Z")]) else [datetime("9437-01-01"), (datetime("1565-10-15T21:45:45.565Z")).offset(duration("0ms"))]).isEmpty())) && false
};
