permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([{"": [[[], [decimal("-131375.5131"), decimal("0.1"), decimal("0.1")]], [[decimal("0.1"), decimal("0.1"), decimal("-810209935786458.7377")], [decimal("0.1"), decimal("-6292903012424.7740"), decimal("-810209935786458.7377")], [decimal("-810209935786458.7377"), decimal("0.1"), decimal("0.0")]]]}[""], []].containsAny([]))) && false) && false
};
