permit(
  principal in jz::a::">>",
  action == jz::Action::"action",
  resource in jz::a::">>"
) when {
  (true && (if (if (action has "UUUUUUU0UUUUU/UUUUUUUUUUUU>>>>>>") then (if true then true else true) else (if true then false else false)) then ((decimal("UUUUUUU0UUUUU/UUUUUUUUUUUU>>>>>>")).lessThan(decimal("UUUUUUU0UUUUU/UUUUUUUUUUUU>>>>>>"))) else ((decimal("UUUUUUU0UUUUU/UUUUUUUUUUUU>>>>>>")).lessThan(decimal("UUUUUUU0UUUUU/UUUUUUUUUUUU>>>>>>"))))) && ((decimal("0.0")).lessThan(decimal("0.0")))
};
