permit(
  principal in a::"",
  action in [Action::"action",Action::"action"],
  resource in a::""
) when {
  (true && (if (if (if false then false else false) then (if false then false else false) else (if false then false else false)) then (if (if false then false else false) then (if false then false else false) else (if false then false else false)) else (if (if false then false else false) then (if false then false else false) else (if false then false else false)))) && (if (if (if false then false else false) then false else false) then false else false)
};
