forbid(
  principal == a::"\n",
  action in [Action::"action"],
  resource
) when {
  ((true && ([[[225301346027464004, 7296960607717360387, 3182967428091151107], [], []], if false then [] else [], if false then [] else []].containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then [decimal("21642678223523.979"), decimal("0.0"), decimal("0.0")] else []))
};
