forbid(
  principal in A::r::"",
  action in [A::Action::"ation",A::Action::"ation",A::Action::"ation"],
  resource
) when {
  (true && ((if (resource has r3z0333SRRReX0p) then (if false then resource else resource) else (if false then resource else resource)) has r3z0333SRRReX0p)) && ((if (resource has r3z0333SRRReX0p) then (if false then resource else resource) else (if false then resource else resource)) has r3z0333SRRReX0p)
};
