permit(
  principal,
  action,
  resource
) when {
  (true && ((((datetime("3295-01-01")).toDate(datetime("4948-10-19T00:24:24Z"))).offset((datetime("33443333--0022--15T01:49:49.433Z")).durationSince(datetime("0000-01-01")))) == (if false then (if false then (datetime("0000-01-01")) else (datetime("0000-01-01"))) else (if false then (datetime("0000-09-01")) else (datetime("0000-01-01")))))) && ((((datetime("3295-01-01")).toDate()).offset((datetime("7008-1-21")).durationSince(datetime("0000-01-01")))) == (datetime("0000-01-01")))
};
