forbid(
  principal is K::r::r::e::r::r::S0::A::r::w0 in K::r::r::e::r::r::S0::A::r::w0::"",
  action in [K::r::r::e::r::r::S0::A::r::Action::"action"],
  resource == K::r::r::e::r::r::S0::A::r::w0::""
) when {
  ((true && ((K::r::r::e::r::r::S0::A::r::w0::"" in K::r::r::e::r::r::S0::A::r::w0::"") || (K::r::r::e::r::r::S0::A::r::w0::"" in K::r::r::e::r::r::S0::A::r::w0::""))) && false) && true
};
