forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource in a::""
) when {
  (true && (((if false then {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]} else {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]})["{{principaE\0\0\0{{z\0\01{{S{S"]).containsAny((if false then {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]} else {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]})["{{principaE\0\0\0{{z\0\01{{S{S"]))) && (((if false then {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]} else {"{{principaE\0\0\0{{z\0\01{{S{S": ["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]})["{{principaE\0\0\0{{z\0\01{{S{S"]).containsAny(["{{principaE\0\0\0{{z\0\01{{S{S", "{{principaE\0\0\0{{z\0\01{{S{S"]))
};
