permit(
  principal in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::r::"vvvvvvvvvvvvvvvv",
  action in [t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::r::""
) when {
  (true && (principal has vvvvvvvvvvvvvvvvvvvvvvvvvvv)) && (principal has vvvvvvvvvvvvvv)
};
