forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if (principal in a::"") then (ip("")) else (action.getTag("Sduration"))).isMulticast())) && (if (({"\u{2}UEUUUUU4444444444444444444444": ip("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/126")}["\u{2}UEUUUUU4444444444444444444444"]).isMulticast()) then ((a::"".getTag("")).isMulticast()) else ((a::"".getTag("")).isMulticast()))) && ((a::"".getTag(if false then "44444444" else "")).isMulticast())
};
