forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"Debian "
) when {
  ((true && ((({"": {"": {"": {"": {"": {}}}, "\u{1e}": {"": {"": {}}}}}}[""])[""]) == (({"": {"": {"": {"": {}}}}}[""])[""]))) && ((({"": {"": {"": {"": {"": {}}}, "@": {"": {"": {}}}}}}[""])[""]) == (({"": {"": {"": {"": {"": {}}}, "|": {}}}}[""])[""]))) && (context == false)
};
