forbid(
  principal in a::"@",
  action == Action::"action",
  resource in a::"V"
) when {
  (true && (((if false then {"+w": ["&[\u{1d}", "&[\u{1d}"]} else {"+w": ["&[\u{1d}", "\u{e}VV"]})["+w"]).containsAny(({"&[\u{1d}": {"+w": [{"&[\u{1d}": ip("565a:eff:2a56:5560e:ff2a:2456:9977:2bff/86")}]}}["&[\u{1d}"])["+w"]))) && (["+w", "+w"].containsAny((if false then {"+w": [""]} else {"+w": ["\u{e}VV"]})["+w"]))
};
