@L00yp7g000vvG0000("")
forbid(
  principal,
  action == Action::"action",
  resource is a in a::"\0\0GGGGGG\0\0{{{\0\0\0{{{SSSSS"
) when {
  ((true && ((true || ("D \'\0\0\0r3D\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}ebian 3\0" like "")) || ("D \'\0\0\0r3D\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}ebian 3\0" like ""))) && ("D \'\0\0\0r3D\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}ebian 3\0" like "")) && ("{E&E\0De\0\0z\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{4}\0\0\0\0\0\0" like "")
};
