forbid(
  principal == t::"",
  action == Action::"action",
  resource in t::""
) when {
  ((true && ((({"": {"": ip("232.255.91.94")}}[""])[""]).isMulticast())) && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then t::"^[\0" else t::""))) && ((decimal("\0\u{2}\0\0\0\0\0\u{2}\0\0")).greaterThan(decimal({VV: "A\0\0"}.VV)))
};
