@Urr3303333("")
@Urr9iiiiii("")
@Urrr0008rr("")
@Urrr3j0000("")
@Urrrrrrrrr("")
@r("")
forbid(
  principal is a in a::" \u{4}",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"\u{17}dc"
) when {
  ((true && ((if ({"": false}[""]) then (if true then {"": context} else {"": {"": {"": {}}, "\0\0\0\u{8}": {"": {}}}}) else ({"": {"": {"": {"": {}}, "\0\0\0\u{8}": {"": {}}}}}[""])) == (({"": {"": {}}}[""])[""]))) && (((if true then {"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t": {"": {"": {"": true}}}} else {"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t": {"": {"": {"": true}}}})["\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"]) == (if ("" like "") then (if true then {"": {"": {"": true}}} else {"": {"": {"": true}}}) else (if true then {"": {"": {"": true}}} else {"": {"": {"": true}}})))) && ("" like "")
};
