@g("")
@q("")
@r("\0\0\u{b}")
@s("")
forbid(
  principal in t::pFFugC04uq123::r::r::r3z0333SRRReX4u::p2::o::r::"=?",
  action == t::pFFugC04uq123::r::r::r3z0333SRRReX4u::p2::o::Action::"action",
  resource in t::pFFugC04uq123::r::r::r3z0333SRRReX4u::p2::o::r::"=?"
) when {
  (true && (Daaaaaaaaa::"" in Daaaaaaaaa::"")) && (r::v::B::r::"" in t::pFFugC04uq123::r::r::r3z0333SRRReX4u::p2::o::r::"=?")
};
