permit(
  principal in dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::a::"",
  action in [dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::Action::"action"],
  resource is dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::a
) when {
  true && (if (true || (dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::a::"" in principal)) then (dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::a::"" in dS::wS::wS::wS::wN::K1ccRRwR2q::r::R::d_::a::"") else ([ip("255.188.188.91/0")] == []))
};
