@B3("ddd")
@DT("")
@LRazE1F("")
@ORbYrYRT33S("")
@U("")
@Xk2000000000000("")
@Xkkkkkkkk5cZgYl("")
@b("")
@d("")
@m("\u{17}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\t\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}")
@pfffffff(")))))))")
@r("")
@r33333333333333("")
@v("")
@x("")
forbid(
  principal is a in a::"\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}[@\u{6}",
  action in [Action::"action"],
  resource == a::"\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}[@\u{6}"
) when {
  true
};
