forbid(
  principal,
  action == Action::"action",
  resource is a in a::"{{{\0\0\0{{{SSSSS"
) when {
  ((true && ((true || ("\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0bian" like "")) || (false && ("\u{1}\u{1}\u{1}ebian 3\0{{E&E\0De\0\0\0\0\0\0" like "")))) && ("\u{1}\u{1}\u{1}ebian 3\0{{E&E\0De\0\0\0\0\0\0" like "")) && ((if true then "\u{1}\u{1}\u{1}ebian 3\0{{E&E\0De\0\0\0\0\0\0" else "") like "")
};
