forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::""
) when {
  ((true && ((if ({} == {}) then ({"": {"": {"": {"": {}}}}}[""]) else (if true then {"": {"": {"": {}}}} else {"": {"": {"": {}}}})) == (({"": {"": {}}}[""])[""]))) && ((({"": {"": {"": {"": {"": {}}}}}}[""])[""]) == (({"": {"": {"": {"": {}}}}}[""])[""]))) && (context == context)
};
