forbid(
  principal in jz::a::">>>",
  action == jz::Action::"action",
  resource in jz::a::">>>"
) when {
  (true && (if (if (action has "UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>") then (if true then false else false) else (if false then false else false)) then (({"UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>": action}["UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>"]) has "UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>") else (if (if false then false else false) then (if true then true else true) else (if false then false else false)))) && ((({UUUUUUUUUUUUUUUUUUUUU: {"UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>": ip("2667:6767:3154:2136:72ff:f01:8a2a:5555/62")}}.UUUUUUUUUUUUUUUUUUUUU)["UUUUUUUUUUUUUUUUUUUUQgggg&U>6>>>>"]).isLoopback())
};
