permit(
  principal,
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ((((ip("2c2c:2c2c:2c2c:2c2c:2c2c:2c2c:2c2c:2c2c")) == (ip("44.44.44.44"))) && ([].containsAny([]))) == ((if false then [] else []).containsAny([decimal("21702051851423.19"), decimal("21702051851423.19"), decimal("318296760487537.495")])))) && ((if ([].containsAny([{}, {}])) then [] else []).containsAny([]))) && false
};
