forbid(
  principal is t::tFFugC04uq123::r::r::r3z333oSRRReX4u::p2::t::vR in t::tFFugC04uq123::r::r::r3z333oSRRReX4u::p2::t::yyqPbop3333::"",
  action == t::tFFugC04uq123::r::r::r3z333oSRRReX4u::p2::t::Action::"vvvvvvv",
  resource is t::tFFugC04uq123::r::r::r3z333oSRRReX4u::p2::t::h0
) when {
  true && (t::tFFugC04uq123::r::r::r3z333oSRRReX4u::p2::t::h0::"".hasTag(if (action.hasTag("555555555555555555")) then "55555" else ""))
};
