permit(
  principal in a::"\0\0\0\0\0\0\0",
  action in [Action::"action"],
  resource in a::"\0\0\0\0\0\0\0"
) when {
  (true && (({"JJJJJJJJJJJ0JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ\0\0\0\0\0\0\0\0": decimal("535312111175163.4978")}["JJJJJJJJJJJ0JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ\0\0\0\0\0\0\0\0"]) == (({"JJJ1JJJJJJJJJJJJJJJJJJJJJJJ!!!!!!!!": context}["JJJ1JJJJJJJJJJJJJJJJJJJJJJJ!!!!!!!!"])["JJJJJJJJJJJJJJJJJDebian JJJ"]))) && true
};
