@LpYD33rrrrrrrLrr("")
@cR("")
@gg3ENNZgD("anV @")
@v("")
forbid(
  principal in a::"V@",
  action == Action::"action",
  resource in a::"V@"
) when {
  (true && (((if false then {"+w": ["&[\u{1d}", "&[\u{1d}"]} else {"+w": ["&[\u{1d}", "\u{e}VV"]})["+w"]).containsAny(({"&[\u{1d}": {"+w": [{"&[\u{1d}": ip("565a:eff:2a56:560e:ff2a:2456:9977:2bff/886")}]}}["&[\u{1d}"])["+w"]))) && (principal in a::"")
};
