forbid(
  principal is a,
  action in [Action::"action",Action::"action"],
  resource == a::"Ų"
) when {
  (true && ((if ({} has "\u{1c}") then (if true then [[context, {"\0\0\u{7}an ": [principal, principal, principal]}, context], [], []] else []) else []).containsAny(if false then (if true then [[false, false], [false, false, true]] else [[false, false], [false, true]]) else (if false then [[false, false], [false, false]] else [[false, false], [], []])))) && false
};
