@Hq("")
@MtttUScccctttt333("")
@booooooooo("")
@l("")
@v("")
@y("")
forbid(
  principal,
  action in [t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::qoqqPbop333::""
) when {
  (true && (principal has "vvvvvvvvvvvvvvvvvvvvvv\u{1}\u{7}\0\u{e}vvvvvvvvvvvvvvvvvvvvvv")) && (if (if (if false then true else true) then ((ip("97..112.14.94/17")).isInRange(ip("94.94.94.94"))) else (resource in resource)) then (t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::ry333S33::"" in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::ry333S33::"") else (t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::f::"" is t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::D))
};
