permit(
  principal is A0,
  action,
  resource is A0
) when {
  ((true && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny([]))
};
