permit(
  principal in a::"",
  action in [Action::"action"],
  resource == a::"\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}}}}}}}}}}}}}}}}}}}}}}}}}}}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}W\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}"
) when {
  (true && ((duration({"15": "15"}["15"])) < (duration({"15": "15"}["15"])))) && ((duration({"15": "15"}["15"])) < (((datetime("6682-03-27T02:26:26-0015")).toDate()).toTime()))
};
