forbid(
  principal is t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::B in t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::r::"",
  action in [t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource is t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::B in t::tFFugC04000z3::r::r::r3z333vSRRReX4u::p2::t::r::"vvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
) when {
  true
};
