@vook("")
permit(
  principal == a::"",
  action,
  resource
) when {
  ((true && ((if ((duration("1176529744197754267ms")) <= (duration("4222406125644786860ms"))) then [{":qqqqqqqoqqqqqqbian \u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}": context, ":qqqqqqqqqqqqqqbian ": {"": ip("2\u{1a}.26.26.26"), "@": "\u{1a}\u{1a}"}}, {":qqqqqqqoqqqqqqbian \u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}": {"": ip("1a20:6e61:990e:2dÿd:249:405b:ff03:1dff"), "@": "\u{3}\u{1d}@"}, ":qqqqqqqqqqqqqqbian ": {"": ip("113.153.20255/14"), "@": "\u{5}["}}, context] else []).contains(context))) && false) && ((if ((-1176529744197754267) <= (-1157442765409259537)) then (principal in [a::"j", a::""]) else (if true then true else false)) || (true || ({} == context)))
};
