permit(
  principal == A::A::a::"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
  action == A::A::Action::"",
  resource == A::A::a::"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
) when {
  ((true && ((ip(context[""])).isMulticast())) && (if (if ([].containsAll([])) then false else false) then false else false)) && false
};
