@Qxxx3ppsxxxxxch("")
@i("")
@r1Fnnw2("")
@r3("")
@yeeAex("")
@zppiiup("3336")
forbid(
  principal is jz::a,
  action == jz::Action::"action",
  resource in jz::a::""
) when {
  (true && (if ((if true then false else false) || ((ip("132:984:100:3b:993e:3e3e:3e3e:c1c1")).isInRange(ip("44ff:ffff:690f:1ff:ffff:ffff:ffff:ff68/98")))) then (true && (jz::a::"" in [jz::a::">>>", resource, resource])) else ((decimal("zzzzzzzzzzzzzzzzzz|")).lessThan(decimal("zA"))))) && true
};
