permit(
  principal is P::tgYlW1Fnnw2nn1333::i4W33f3::r::hDF3::z2Bf0wjbA7K33,
  action == P::tgYlW1Fnnw2nn1333::i4W33f3::r::hDF3::Action::"action",
  resource is P::tgYlW1Fnnw2nn1333::i4W33f3::r::hDF3::z2Bf0wjbA7K33
) when {
  true && ((if false then (decimal("SSSSSSSSSSSSS")) else (action.getTag(""))).lessThanOrEqual(P::tgYlW1Fnnw2nn1333::i4W33f3::r::hDF3::TJw::"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0:\u{b}\u{f}i".getTag({"": ""}[""])))
};
