permit(
  principal == r::r::A2d::r::a::"\0",
  action == r::r::A2d::r::Action::"action",
  resource == r::r::A2d::r::a::"\0"
) when {
  true && ((Ch::ULLLLLLLhhhh::b7777ppppppp::z::Uhhhhhhhhhhh::UhhhhhhZZZZZ::CZZZZZZZZ::CZZZZ9s0Z::A0::"" in z::z::Uhhhhhhhhhhh::UhhZZZZZZZZZ::CZZZZZZvZ::K9js0ZZZZ::z::"") || (UhZZZZZZZZZZ::CZZZZZZZ9::L::L::L::C::Ts0ZZZZZZ::CZZZZZZZZ::Uhhhhhhhh::"" in A::A::A::A::A::A::A::A::CZZZZYc00::""))
};
