@A("")
permit(
  principal,
  action == Action::"action",
  resource == a::""
) when {
  true && (!((if false then (if false then (duration("0ms")) else (duration("9061242450269437952ms"))) else ((datetime("3410-11-07T10:10:52")).toTime())) <= (duration({"\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}~\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}": "\u{14}\u{14}\u{14}\u{14}\u{14}\u{14}\u{14}*D[ba"}["\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}~\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}"]))))
};
