@erG10("")
permit(
  principal,
  action == A::A::j00000U000::Action::"action",
  resource in A::A::j00000U000::ATrqq3TFqqqVpr::"\0G"
) when {
  (true && ([A::A::j00000U000::ATrqq3TFqqqVpr::"\0G" is A::A::j00000U000::ATrqq3TFqqqVpr, A::A::j00000U000::ATrqq3TFqqqVpr::"\0G" is A::A::j00000U000::ATrqq3TFqqqVpr, resource is A::A::j00000U000::ATrqq3TFqqqVpr].containsAny([(ip("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/126")).isMulticast(), A::A::j00000U000::ATrqq3TFqqqVpr::"\0G" is A::A::j00000U000::ATrqq3TFqqqVpr, A::A::j00000U000::ATrqq3TFqqqVpr::"\0G" is A::A::j00000U000::ATrqq3TFqqqVpr]))) && (((if false then context else context)["55555550000\u{10}\u{10}\0\0\0\0\0\0\u{5}\0\0\0\0?!\0"]) is A::A::j00000U000::ATrqq3TFqqqVpr)
};
