permit(
  principal,
  action in [QI00dppp::ID000pppppppn::Ippppppppp100::M::Action::""],
  resource in QI00dppp::ID000pppppppn::Ippppppppp100::M::a::""
) when {
  ((true && ((if (QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" in QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"") then (if true then QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" else QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"") else (if true then QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" else QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"")) in (if (QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" in QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"") then (if true then QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" else QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"") else (if true then QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" else QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"")))) && ((if (QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" in QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"") then (if true then QI00dppp::ID000pppppppn::Ippppppppp100::M::a::"" else resource) else A::A::A::A::A::A::MA3335fOY0000::"") in principal)) && false
};
