forbid(
  principal is r::r::A::A::A::A::G661333::a in r::r::A::A::A::A::G661333::a::"",
  action in [r::r::A::A::A::A::G661333::Action::"action",r::r::A::A::A::A::G661333::Action::"action",r::r::A::A::A::A::G661333::Action::"action"],
  resource is r::r::A::A::A::A::G661333::a in r::r::A::A::A::A::G661333::a::""
) when {
  ((true && (434041037028460038 <= 434041037028460038)) && true) && true
};
