@dgggg00000000("")
forbid(
  principal == r::A::Lc::"",
  action in [r::A::Action::"action"],
  resource
) when {
  ((true && ((r::A::D::"S".getTag(r::A::D::"S".r)) == (if (r::A::A00RRw33RST::"\u{1d}\u{1d}S\0\0" in r::A::vR::"?EEEEEEEEEEEE4444444444444444444444FFFFFFFFFFFFFFFFFFFFFF") then (principal.getTag("k\u{c}\u{c}\u{c}")) else ({"": datetime("026-\02-24T13:25:25.084Z")}[""])))) && ((false || (action in action)) || (resource in action))) && true
};
