permit(
  principal,
  action in [Action::"action"],
  resource == a::"/h"
) when {
  ((true && ((if ({"\u{82}\u{2}": false}["\u{82}\u{2}"]) then (if false then {"": false} else context) else (if true then context else {"": false}))[""])) && ((if true then (if false then {"#": false} else {"#": false}) else (if false then context else context))["#"])) && ((if ({"": true}[""]) then (if false then {"\'\u{18}": false} else {"\'\u{18}": false}) else {"\'\u{18}": true})["\'\u{18}"])
};
