@kEEEEEEEEUEEEEEEE("")
@sEDEEUEEEEEEEEEEE("")
@sEEEEEEEEEEEEEEE0("")
@sEEEEEEEEEEEEEEEE("")
@sEEEEEEEEEEEEEEKE("")
@sEEEEEEEEEEEEX0D0("")
@sEEEEEEEEEEEX0D0E("")
@sEEEUEEEEEEEEEEEE("A")
@sEEEmEEEEX0D010EE("")
@sEEKEEEEEEEEEEEEE("")
@sUEEEEEEEEEEEEEEE("")
forbid(
  principal is A::a,
  action == A::Action::"action",
  resource is A::a
) when {
  ((true && ((ip("")) == (ip("")))) && ((ip("")) == (ip("")))) && ((ip("")) == (ip("")))
};
