forbid(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((({"lll\'": [[[true, true, true], [true, true, true], [false, false]], [[false, false], []], [[true, false]]]}["lll\'"]).containsAll(if true then [] else [a::"", a::"", a::""])) && true)) && ((([["", ""], ["", ""]].containsAll([])) && false) && false)) && false
};
