forbid(
  principal,
  action in [r::V::QN::r::Action::"action"],
  resource
) when {
  ((true && (((r::V::QN::r::A::"".GRRmST3N).GRRmST3N) in ((r::V::QN::r::A::"".GRRmST3N).GRRmST3N))) && (((r::V::QN::r::A::"".GRRmST3N).GRRmST3N) in ((r::V::QN::r::A::"".GRRmST3N).GRRmST3N))) && (if ((r::V::QN::r::A::"".GRRmST3N) in (r::V::QN::r::A::"".GRRmST3N)) then ((r::V::QN::r::A::"".GRRmST3N) in (r::V::QN::r::A::"".GRRmST3N)) else ((r::V::QN::r::A::"".GRRmST3N) in r::V::QN::r::A::" \'\0\0\0r33$/333336"))
};
