forbid(
  principal is a,
  action == Action::"action",
  resource is a
) when {
  ((true && (if (if (if false then false else false) then false else false) then (false && ([{mmmmmmmmmmmmmmmmm: 7885078839350357357}].containsAll([{m: 7885078839356255597}]))) else (({"": [{"": {"": 7885078839350357357}}]}[""]).containsAll([{"": {"mmmmmmPP/PP\0": (-4485090715809758783)}}])))) && (if true then false else false)) && false
};
