permit(
  principal in t::tFFugC04000z3::r::r::r3z333kSRRReX4u::p2::t::r::"\0\0\0\0\0\0\0\0\0\0vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
  action in [t::tFFugC04000z3::r::r::r3z333kSRRReX4u::p2::t::Action::"action",t::tFFugC04000z3::r::r::r3z333kSRRReX4u::p2::t::Action::"action"],
  resource in t::tFFugC04000z3::r::r::r3z333kSRRReX4u::p2::t::r::"\0\0\0\0\0\0\0\0\0\0vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
) when {
  (true && (principal has vvvvvvvvvvvvvvvvvvvvvvv)) && (principal has "H5vvvvvvvvvvvvvvvvvfvvv][")
};
