permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource
) when {
  ((true && ((if (resource has A) then (if false then resource else resource) else (if false then resource else resource)) has A)) && ((if (resource has A) then (if false then resource else resource) else (if false then resource else resource)) has A)) && ((if (resource has A) then (if false then resource else resource) else (if false then resource else resource)) has A)
};
