forbid(
  principal == R::Q000ddZZZr9s0ZZ::roZZZZZZZ::CZZZZhhh1::vRRR::tgYlW002dd00dHHHH::U::"",
  action == R::Q000ddZZZr9s0ZZ::roZZZZZZZ::CZZZZhhh1::vRRR::tgYlW002dd00dHHHH::Action::"action",
  resource == R::Q000ddZZZr9s0ZZ::roZZZZZZZ::CZZZZhhh1::vRRR::tgYlW002dd00dHHHH::U::""
) when {
  true && (l::r00ddZZZr9s::C::C3oZZhhhh::CZZZZZZZZZZZ::a::"" in i44441g::i4ddYcl::A::A::A::A::A::A::i444444::"")
};
