@B("")
@B33344("")
@EW1Fnnw2nn133("B")
@J1W33("")
@O("C:\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}\u{1}")
@P("bian \u{1}\u{f}")
@P2nl13("")
@Pg("")
@Pn("yA")
@TJJ("")
@_31Fnnw2nn133344("\'ggg\ngfg")
@_YlW1Fnnw2nn13("")
@eKKKKKKKKKKKKKKK("SSSSyASSSSSS1SSSSSSSSSS")
@i433enw("")
@i4W33f3("")
@i4deeeA("gg")
@iW33f33("")
@ideeeAe("g")
@r("")
@r33333("\u{1}\u{f}i")
@w("")
forbid(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a
) when {
  ((true && (!((a::"" in [a::"", action, action]) && ([(datetime("5535-02-08T15:43:43.663-1313")).offset(duration("-0d0h0s"))].containsAll([(datetime("5535-04-08T08:32:15.707+0823")).offset(duration("-0d0h0m0s0ms")), (datetime("1331-1\u{13}\u{b}22T07:01:15.473+1332")).offset(duration("-0h0m0s0ms")), (datetime("0511-04-08T01:49:39.471+1015")).offset(duration("-0d0h0m0s0ms"))]))))) && (((0 + 0) + (0 + 0)) == ((0 + 0) + (0 + 0)))) && (if (if (a::"" in [resource, a::"", a::""]) then (if true then true else true) else ((ip("6767:6727:c1c1:c1ff:ffff:1ad:af41:4179")).isInRange(ip("5353:5353:5353:2f53:5353:5353:5353:3153/83")))) then true else true)
};
