permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource in a::"FFFFFFFFFFFFFF\0"
) when {
  ((true && (((false == false) == (false == false)) == ((false == true) == (principal in resource)))) && (((false == false) == ("\0\0\0\0\0\0\0FFFFFFFFFFFFFF\0" == "")) == ((if false then {} else {}) has "------------444444dqqq44444444||||||||||||||||||||||||||||||||"))) && (if (if (if false then false else false) then (false == false) else ({} has "FFFFFFFFF4\0\0\0\0\0\0\0FFFFFFFFFFFFFF\0")) then ((if false then {} else {}) has "------------444444dqqq444") else (a::"FFFFFFFFFFFFFF\0" has "4||||||||||||||||||||||||||||||||||||||||||||||||||||44"))
};
