permit(
  principal is t,
  action == Action::"5555",
  resource
) when {
  (true && (((principal in resource) || (1080750912556302401 <= (-181014141953639))) || (true && (!((datetime("9624-05-16")) <= (datetime("9624-05-16"))))))) && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then (if false then principal else principal) else (if false then resource else t::"@@@@@@@@@@@\u{2}\0\u{3}\0\0\0\0\0\0\0\u{2}\0\u{3}\u{1d}N\0")))
};
