permit(
  principal == a::"",
  action in [Action::""],
  resource
) when {
  ((true && (if ((if true then (decimal("471187351474798.5920")) else (decimal("5.2428"))) == (if false then (decimal("0.0")) else (decimal("0.0")))) then false else ((decimal("")) == (decimal(""))))) && ((decimal("")) == (decimal("")))) && ((decimal("")) == (if ((decimal("-368934881474191.324")) == (decimal("0.0"))) then (decimal("0.0")) else (decimal("0.0"))))
};
