forbid(
  principal in a::"",
  action,
  resource
) when {
  (true && ((if (context[";kk\n"]) then [[[{}, {}, {}], [{}, {}, {}], [{}, {}, {}]], [[{}, {}], [], []], [[{}, {}, {}], [{}, {}, {}], [{}, {}, {}]]] else ({"\u{7f}{\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}": [[[context, {}, context], [{}], [{}, {}, {}]], [[{}, {}, {}], [{}, {}, {}], [{}, context, context]], [[], [], []]]}["\u{7f}{\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}"])) == (duration("0ms")))) && false
};
