forbid(
  principal == t::"^[\0",
  action == Action::"action",
  resource in t::""
) when {
  ((true && ((({"": {"": ip("232.255.91.94")}}[""])[""]).isMulticast())) && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)))) && ((if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)) in (if (principal in principal) then (if false then principal else principal) else (if false then principal else principal)))
};
