permit(
  principal,
  action in [Action::"action"],
  resource == a::""
) when {
  (true && ((if (if false then false else false) then ({"\u{1} ": {"": false}}["\u{1} "]) else {"": true})[""])) && ((if ((decimal("-90425072531687.3089")) == (datetime("5847-07-07T10:02:10Z"))) then ((datetime("8316-09-03")).toDate()) else (context["\0"])) == (({":0": (datetime("4848-07-28")).offset(duration("48446677991155880011551100005506m"))}[":0"]).toDate()))
};
