permit(
  principal in a::"\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}}}}}}}}}}}",
  action in [Action::"action"],
  resource in a::"\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}}}}}}}}}}}"
) when {
  (true && ((duration(context["\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"])) < (if false then (if false then (duration("0ms")) else (duration("0ms"))) else (if false then (duration("0ms")) else (duration("1880844493789998618ms")))))) && (!((if false then (if false then (duration("0ms")) else (duration("0ms"))) else (if false then (duration("0ms")) else (duration("1880844493789993695ms")))) <= (if true then (duration("-55444593988434d")) else (duration("0ms")))))
};
