@A("")
@F("")
@K("")
@P("")
@PccccVc("")
@Pcccccc("")
@bc("")
@gd000cPgYWccc("")
@hcccccc("")
@n____eYBZg____("")
@nk_ccccccccc33("")
@r("")
@u("")
@u3("\0\0")
@uG("")
@v3ERJST1("")
@vJST1Rccccccc00("")
@ybmmmaH("")
permit(
  principal == a::"\0\0\0\0\0**",
  action == Action::"action",
  resource == a::"\0\0\0\0\0**"
) when {
  ((true && (resource in resource)) && (resource in resource)) && (resource in a::"\0\0\0\0\0**")
};
