@A008rrrrrr("")
@Urrrrrrrrr("")
@rj33000000("")
forbid(
  principal is a in a::"\'\0",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"\'\0"
) when {
  ((true && ((if ({} == {"": decimal("\u{8b}\u{8b}\u{8b}³³³³\n04921689.|\u{8b}\u{8b}\u{8b}")}) then ({"": {"": {}}}[""]) else ({"": {"": {}}}[""])) == (({"": {"": {}}}[""])[""]))) && ((({"\t": {"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t": {"": {"": {"": true}}}}}["\t"])["\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"]) == ((if true then {"\t": {"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t": {"": {"": true}}}} else {"\t": {"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t": {"": {"": true}}}})["\t"]))) && ("" like "")
};
