@A("")
forbid(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((({"": {"": {"": a::""}}}[""])[""]) has "")) && ((({"": {"": {"": a::"", "/": a::""}}}[""])[""]) has "")) && ((if ({"": principal} has "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0") then {"": datetime("0000-01-30")} else {"": datetime("0000-01-01")}) has "\0\0\0\0\0\0\0\0")
};
