forbid(
  principal in jz::a::"",
  action in [jz::Action::"action"],
  resource in jz::a::""
) when {
  (true && (if (({"UUUUUUUUDebian UUUUUUUUUUUU|||||||U": {}}["UUUUUUUUDebian UUUUUUUUUUUU|||||||U"]) has "UUUUUUUUDebian UUUUUUUUUUUU|||||||U") then (({"UUUUUUUUDebian UUUUUUUUUUUU|||||||U": {}}["UUUUUUUUDebian UUUUUUUUUUUU|||||||U"]) has "UUUUUUUUDebian UUUUUUUUUUUU|||||||U") else (({"UUUUUUUUDebian UUUUUUUUUUUU|||||||U": {}}["UUUUUUUUDebian UUUUUUUUUUUU|||||||U"]) has "UUUUUUUUDebian UUUUUUUUUUUU|||||||U"))) && ({} has "UUUUUUUUDebian UUUUUUUUUUUU|||||||U")
};
