@MC22222MMMMMM("\u{c}\u{c}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}")
@dTTTTTT3_4HH3("")
@dTTTggggggggg("iiii----44444444444444444464\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}\u{1d}")
@r("")
permit(
  principal in r::A::r33::">",
  action == r::A::Action::"iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii",
  resource is r::A::r33
) when {
  true
};
