forbid(
  principal == a::"\n",
  action == Action::"action",
  resource == a::"\n"
) when {
  ((true && ([[[225301346027464004, 7296960607717360387, 217020518514230019], [217020518514230019, 5931244020717257475, 3182967604872676099], []], if false then [] else [], if false then [] else []].containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])))) && ((if ([].containsAny([])) then (if false then [] else []) else (if false then [] else [])).containsAny(if ([].containsAny([])) then (if true then [decimal("24347960\u{82}94856.6787"), decimal("0.0"), decimal("0.0")] else []) else []))
};
