@sEEEEEEEEEEX0D010("")
permit(
  principal in A::WjjjKLLLj2jfcZ::A::"\0\0\0\0\0",
  action == A::WjjjKLLLj2jfcZ::Action::"action",
  resource in A::WjjjKLLLj2jfcZ::A::"\0\0\0\0\0"
) when {
  (true && (((if false then {"": ["\0", ""]} else {"": ["", "", ""]})[""]).containsAny(({"": {"": [ip("203.203.203.203/5"), ip("cbcb:cbcb:cbcb:cbcb:cbcb:cbcb:cbcb:3ccb/74"), ip("cbcb:cbcb:cbcb:cbcb:cbcb:cbcb:cbcb:cbcb/53")]}}[""])[""]))) && ((ip("")) == (ip("")))
};
