permit(
  principal,
  action,
  resource
) when {
  (true && ((((datetime("3295-01-01")).toDate(datetime("4948-10-19T00:24:24Z"))).offset((datetime("7008-01-21T10:02:10-1315")).durationSince(datetime("5954-10-0508:00:00Z")))) == (if false then (if false then (datetime("0000-01-01")) else (datetime("0000-01-01"))) else (if false then (datetime("69332-0-06T01:50:07Z")) else (datetime("0000-01-01")))))) && false
};
