forbid(
  principal == a::"\u{f}@",
  action == Action::"action",
  resource is a in a::"\u{f}@"
) when {
  ((true && ([].contains({"": {"": datetime("0000-01-01"), "\0\u{7}\0\0``````": "\0\0\0\0\0\0\u{e}", "שּׁ": {"": datetime("9251-08-02")}}, "\0\0\u{7}\0\0!": {"שּׁ": context}, "``": {"`": duration("0ms"), "```````````````````````````": decimal("0.0"), "```````````````````````````````````````````````": {"!": (datetime("8059-06-07T08:00:00Z")).offset(duration("4919131752996038336h187m"))}}}))) && false) && false
};
