forbid(
  principal == a::"",
  action == Action::"action",
  resource is a
) when {
  true && (if (if (action in action) then (if false then false else false) else false) then false else (({mmmmm: [{mmmmmmmmmmmmmm: {mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm: 7885078839350357357}}]}.mmmmm).containsAll([context, {"\u{e}\u{e}\0\0\0\0\0\0\0\0\0\u{e}\u{e}\0": {"mmmmmmmm\u{15}\u{15}mmmmmmm\u{15}\u{15}\u{15}\u{15}\u{15}m\u{15}\u{15}\u{15}\u{15}": (-3802463450)}}, {"\u{e}\u{e}\0\0\0\0\0\0\0\0\0\u{e}\u{e}\0": {"mmmmmmmm\u{15}\u{15}mmmmmmm\u{15}\u{15}\u{15}\u{15}\u{15}m\u{15}\u{15}\u{15}\u{15}": 1080597889130233664}}])))
};
