permit(
  principal,
  action in [w::Action::"action",w::Action::"action"],
  resource in w::a::""
) when {
  ((true && (((false == false) == (false == false)) == ((false == false) == ((ip("70.70.70.70")).isIpv4(ip("70.70.70.70"), ip("122.10.169.0")))))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && (((false == false) == (principal has "4444")) == (w::a::"FFFFFFFFFFFF\0" has "0///////"))
};
