forbid(
  principal == a::"\u{f}@",
  action == Action::"action",
  resource is a in a::"\u{f}@"
) when {
  ((true && ((if ([{"": {}}, {"": {}}, {"": context}].contains({"": {}})) then [{"": {"": {"": 5136152271503443783}}}, {"": {"": {"": 5136152271503443783}}}, {"": {"": {"": 5136152271503443783}}}] else ({"GGGGGGG@SGG\0": [{"": {"": {"": 1095764262971}}}]}["GGGGGGG@SGG\0"])).contains(context))) && false) && false
};
