permit(
  principal in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::r::"\0\0vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv",
  action in [t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action",t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::Action::"action"],
  resource in t::tFFugC04uq123::r::r::r3z333vSRRReX4u::p2::t::r::"\0\0vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
) when {
  (true && (principal has "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv][")) && (principal in principal)
};
