@n__00000000000("")
permit(
  principal is r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a in r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::"Ԕ",
  action == r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::Action::"action",
  resource == r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::""
) when {
  ((true && (r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::"".hasTag(""))) && (r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::"".hasTag(if (r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::"".hasTag("")) then (if true then "" else "") else (if true then "" else "")))) && (r::r::R::Q000ddZZcZgYlWl::v6000llWQQQQQQ::tgYl2W00dd00dHHHH::a::"".hasTag(""))
};
