@m00("")
forbid(
  principal,
  action in [Action::"action"],
  resource == a::""
) when {
  ((true && (if (if (if true then true else true) then (if true then false else true) else (if true then true else true)) then (if (if true then false else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else false) else false)
};
