permit(
  principal in a::"\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}r\0\u{1}\u{f}\0\u{1}\0\u{17}\u{f}r\0",
  action in [Action::"action"],
  resource in a::"\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}\u{1a}r\0\u{1}\u{f}\0\u{1}\0\u{17}\u{f}r\0"
) when {
  (true && (!((duration({"15": "15"}["15"])) < (duration({"15": "15"}["15"]))))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then ((duration("15")) < (duration("15"))) else ((duration("15")) < (duration("15"))))
};
