forbid(
  principal in K::r333r3333Sf000hSS::A::w::A00S::ukkkx::CPPPPPPPPPP::CPPPPPPPPPP::r::a::"",
  action in [K::r333r3333Sf000hSS::A::w::A00S::ukkkx::CPPPPPPPPPP::CPPPPPPPPPP::r::Action::"action"],
  resource in K::r333r3333Sf000hSS::A::w::A00S::ukkkx::CPPPPPPPPPP::CPPPPPPPPPP::r::a::""
) when {
  (true && ((false && ("..+..........................................." like "*****")) && ("." like ""))) && ((".+..............." like "") && false)
};
